self:
  id: 1
  ip: 127.0.0.1
  port: 40001
remote:
  - id: 2
    ip: 192.168.31.102
    port: 30001
    send_topics:
      - /robot2/cmd_vel #geometry_msgs::Twist
      - /robot2/cat_cmd #std_msgs::Bool
    recv_topics:
      - /robot2/Odometry #nav_msgs::Odometry
      - /robot2/cat_state #std_msgs::Bool
      - /robot2/imu #message::Bool
  - id: 3
    ip: 192.168.31.103
    port: 30001
    send_topics:
      - /robot3/cmd_vel #geometry_msgs::Twist
      - /robot3/cat_cmd #std_msgs::Bool
    recv_topics:
      - /robot3/Odometry #nav_msgs::Odometry
      - /robot3/cat_state #std_msgs::Bool